/* eslint-disable no-alert */
import React, { Component } from 'react';
import { withRouter } from 'react-router-dom';
import Phone from '../img/phone.svg';

class Contact extends Component {
  constructor(props) {
    super(props);
    this.state = {
      fn: '',
      ln: '',
      msg: '',
      phone: '',
      email: '',
      ad: '',
    };
  }

  stateSetter = (event) => {
    const { name, value } = event.target;
    this.setState({ [name]: value });
  }

  phoneTab = () => {
    alert('Please Call us at: '); // Fill in Phone Number and Email Address
  }

  sendEmail = () => {
    if (this.state.fn === '' || this.state.ln === '' || this.state.email === '' || this.state.phone === '') {
      alert('Please Fill out all required fields in the Form!');
    } else {
      let body = `
          -----The below message was auto-generated by the Contact Us form on the Vibrant Heart Website-----\n\n
          First name: ${this.state.fn}\n\n
          Last name: ${this.state.ln}\n\n 
          Email: ${this.state.email}\n\n
          Phone: ${this.state.phone}\n\n
          Custom Message:\n
          ${this.state.msg}\n\n
          Additional Details: \n
          ${this.state.ad}
        `;
      body = encodeURIComponent(body);
      window.location.href = `mailto:email_goes_here?cc=${this.state.email}&body=${body}&subject=Vibrant Heart Question`;
      alert('Your email has been successfully generated. Please use your native email client to send the message!');
    }
  }

  render() {
    return (
      <div className="contact-page">
        <div className="contact-title">
          How can we help?
        </div>
        <div className="contact-box">
          <div className="contact-rows">
            <div className="left-row">
              <div className="FN-box">
                <input type="text" id="fn" name="fn" placeholder="First Name" value={this.state.fn} onChange={this.stateSetter} />
              </div>
              <div className="Email-Box">
                <input type="text" id="email" name="email" placeholder="Email" value={this.state.email} onChange={this.stateSetter} />
              </div>
              <div className="Contact-Msg">
                <textarea maxLength="250" id="msg" name="msg" placeholder="Message" value={this.state.msg} onChange={this.stateSetter} />
              </div>
            </div>
            <div className="right-row">
              <div className="LN-box">
                <input type="text" id="ln" name="ln" placeholder="Last Name" value={this.state.ln} onChange={this.stateSetter} />
              </div>
              <div className="Phone-Box">
                <input type="text" id="phone" name="phone" placeholder="Phone number" value={this.state.phone} onChange={this.stateSetter} />
              </div>
              <div className="AD">
                <textarea maxLength="250" id="ad" name="ad" placeholder="Additional Details" value={this.state.ad} onChange={this.stateSetter} />
              </div>
            </div>
          </div>
          <div className="contact-button" role="button" tabIndex={0} onClick={this.sendEmail}>
            Submit
          </div>
        </div>
        <div className="contact-buttons">
          <div className="phone-sec" role="button" tabIndex={0} onClick={this.phoneTab}>
            <img src={Phone} alt="phone" className="limit" />
            <div className="bottom-text">
              Call us!
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default withRouter((Contact));
